# Generated by Django 5.2.17 on 2026-09-29 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('archived', 'Archived')], default='ready', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_uses', to='questions.question')),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocks.mocktest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mock', 'order')},
            },
        ),
    ]
