# Generated by Django 5.2.17 on 2026-09-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('both', 'Both')], default='english', max_length=10),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('both', 'Both')], default='english', max_length=10),
        ),
    ]
