# Generated by Django 5.2.17 on 2026-09-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionexplanation',
            name='text_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionexplanation',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
