# Generated by Django 5.2.17 on 2026-09-29 09:21

import apps.exams.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('instructions', models.TextField(blank=True)),
                ('difficulty_distribution', models.JSONField(default=apps.exams.models.default_difficulty)),
                ('question_types', models.JSONField(default=apps.exams.models.default_question_types)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='PatternSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField()),
                ('marks_per_question', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exampattern')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.subject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams.subject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
