# Generated by Django 5.2.16 on 2026-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternsection',
            name='subject',
        ),
        migrations.AddField(
            model_name='patternsection',
            name='subjects',
            field=models.ManyToManyField(related_name='pattern_sections', to='exams.subject'),
        ),
    ]
