# Generated by Django 5.2.17 on 2026-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_patternsection_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
