# Generated by Django 5.2.17 on 2026-09-29 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocks', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mocks.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('attempted', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('incorrect', models.PositiveIntegerField()),
                ('unattempted', models.PositiveIntegerField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_used_seconds', models.PositiveIntegerField()),
                ('analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='attempts.testsession')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mock_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.mockquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.testsession')),
            ],
            options={
                'unique_together': {('session', 'mock_question')},
            },
        ),
    ]
